resume_training: true
series_name: l:xyz, anisotropy tensor

hydra:
  run:
    dir: ${oc.env:PROJECT_ROOT}/out/mcconkey/phll_1p2_rperp_opt_16c

defaults:
  - data: e3_rst_rperp_opt
  - model: default_xy

model:
  nn:
    hidden_irreps: "16x0e + 16x1e + 16x1o + 16x2e"




training:
  trainer:
      max_epochs: 1000
      gpus: 1
      progress_bar_refresh_rate: 50

# test xy and xyz in training

  batch_size: 512
  lr: 1e-3
  weight_decay: 1.0e-5

# maybe test lower lr? (doesn't help on RFV, though)

injection:
  save_dir: ${oc.env:PROJECT_ROOT}/out/mcconkey/phll_1p2_rperp_opt_16c
  save_name: rperp_opt_out_16c_cond
  template_path: ${oc.env:PROJECT_ROOT}/config/mcconkey/templates/rperp
  dimensions: 'xy'